package com.base.model;

public class Evaluate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.id
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.oid
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.content
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.createtime
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private String createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.id
     *
     * @return the value of evaluate.id
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.id
     *
     * @param id the value for evaluate.id
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.oid
     *
     * @return the value of evaluate.oid
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.oid
     *
     * @param oid the value for evaluate.oid
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.content
     *
     * @return the value of evaluate.content
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.content
     *
     * @param content the value for evaluate.content
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.createtime
     *
     * @return the value of evaluate.createtime
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.createtime
     *
     * @param createtime the value for evaluate.createtime
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }
}