package com.base.model;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.createtime
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.status
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private String statu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.commont
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private String commont;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.createtime
     *
     * @return the value of role.createtime
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.createtime
     *
     * @param createtime the value for role.createtime
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }


    public String getStatu() {
		return statu;
	}

	public void setStatu(String statu) {
		this.statu = statu;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.commont
     *
     * @return the value of role.commont
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public String getCommont() {
        return commont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.commont
     *
     * @param commont the value for role.commont
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setCommont(String commont) {
        this.commont = commont;
    }
}