package com.base.model;

public class Rolemenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolemenu.id
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolemenu.rid
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolemenu.mid
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private Integer mid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolemenu.id
     *
     * @return the value of rolemenu.id
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolemenu.id
     *
     * @param id the value for rolemenu.id
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolemenu.rid
     *
     * @return the value of rolemenu.rid
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolemenu.rid
     *
     * @param rid the value for rolemenu.rid
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolemenu.mid
     *
     * @return the value of rolemenu.mid
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolemenu.mid
     *
     * @param mid the value for rolemenu.mid
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }
}