package com.base.model;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.uid
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.createtime
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.statu
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private String statu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address
     *
     * @return the value of address.address
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address
     *
     * @param address the value for address.address
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.uid
     *
     * @return the value of address.uid
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.uid
     *
     * @param uid the value for address.uid
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.createtime
     *
     * @return the value of address.createtime
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.createtime
     *
     * @param createtime the value for address.createtime
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.statu
     *
     * @return the value of address.statu
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public String getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.statu
     *
     * @param statu the value for address.statu
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setStatu(String statu) {
        this.statu = statu;
    }
}