package com.base.model;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Fri Jun 23 15:36:25 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbggenerated Fri Jun 23 15:36:25 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.createTime
     *
     * @mbggenerated Fri Jun 23 15:36:25 CST 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.status
     *
     * @mbggenerated Fri Jun 23 15:36:25 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.commont
     *
     * @mbggenerated Fri Jun 23 15:36:25 CST 2017
     */
    private String commont;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated Fri Jun 23 15:36:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated Fri Jun 23 15:36:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbggenerated Fri Jun 23 15:36:25 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbggenerated Fri Jun 23 15:36:25 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.createTime
     *
     * @return the value of role.createTime
     *
     * @mbggenerated Fri Jun 23 15:36:25 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.createTime
     *
     * @param createtime the value for role.createTime
     *
     * @mbggenerated Fri Jun 23 15:36:25 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.status
     *
     * @return the value of role.status
     *
     * @mbggenerated Fri Jun 23 15:36:25 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.status
     *
     * @param status the value for role.status
     *
     * @mbggenerated Fri Jun 23 15:36:25 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.commont
     *
     * @return the value of role.commont
     *
     * @mbggenerated Fri Jun 23 15:36:25 CST 2017
     */
    public String getCommont() {
        return commont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.commont
     *
     * @param commont the value for role.commont
     *
     * @mbggenerated Fri Jun 23 15:36:25 CST 2017
     */
    public void setCommont(String commont) {
        this.commont = commont;
    }
}