package com.base.model;

public class ShopType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoptype.id
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoptype.name
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoptype.createtime
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoptype.statu
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    private String statu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoptype.id
     *
     * @return the value of shoptype.id
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoptype.id
     *
     * @param id the value for shoptype.id
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoptype.name
     *
     * @return the value of shoptype.name
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoptype.name
     *
     * @param name the value for shoptype.name
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoptype.createtime
     *
     * @return the value of shoptype.createtime
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoptype.createtime
     *
     * @param createtime the value for shoptype.createtime
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoptype.statu
     *
     * @return the value of shoptype.statu
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    public String getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoptype.statu
     *
     * @param statu the value for shoptype.statu
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    public void setStatu(String statu) {
        this.statu = statu;
    }
}