package com.base.model;

public class Shop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.id
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.name
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.img
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.price
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.discountprice
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private Double discountprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.statu
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private String statu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.createtime
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.updatetime
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.id
     *
     * @return the value of shop.id
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.id
     *
     * @param id the value for shop.id
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.name
     *
     * @return the value of shop.name
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.name
     *
     * @param name the value for shop.name
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.img
     *
     * @return the value of shop.img
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.img
     *
     * @param img the value for shop.img
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.price
     *
     * @return the value of shop.price
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.price
     *
     * @param price the value for shop.price
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.discountprice
     *
     * @return the value of shop.discountprice
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public Double getDiscountprice() {
        return discountprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.discountprice
     *
     * @param discountprice the value for shop.discountprice
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setDiscountprice(Double discountprice) {
        this.discountprice = discountprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.statu
     *
     * @return the value of shop.statu
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public String getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.statu
     *
     * @param statu the value for shop.statu
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setStatu(String statu) {
        this.statu = statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.createtime
     *
     * @return the value of shop.createtime
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.createtime
     *
     * @param createtime the value for shop.createtime
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.updatetime
     *
     * @return the value of shop.updatetime
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.updatetime
     *
     * @param updatetime the value for shop.updatetime
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime;
    }
}