package com.base.mapper;

import com.base.model.Evaluate;

public interface EvaluateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    int insert(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    int insertSelective(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    Evaluate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    int updateByPrimaryKeySelective(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    int updateByPrimaryKey(Evaluate record);
}