package com.base.mapper;

import com.base.model.Rolemenu;

public interface RolemenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    int insert(Rolemenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    int insertSelective(Rolemenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    Rolemenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    int updateByPrimaryKeySelective(Rolemenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated Tue Jun 27 13:46:53 CST 2017
     */
    int updateByPrimaryKey(Rolemenu record);
}