package com.base.mapper;

import com.base.model.ShopType;

public interface ShopTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoptype
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoptype
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    int insert(ShopType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoptype
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    int insertSelective(ShopType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoptype
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    ShopType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoptype
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    int updateByPrimaryKeySelective(ShopType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoptype
     *
     * @mbggenerated Sat Jul 08 12:00:02 CST 2017
     */
    int updateByPrimaryKey(ShopType record);
}