package com.xsx.domain;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_name
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_py
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String cityPy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.prov_id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private Integer provId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_state
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String cityState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.id
     *
     * @return the value of city.id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.id
     *
     * @param id the value for city.id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_id
     *
     * @return the value of city.city_id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_id
     *
     * @param cityId the value for city.city_id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_name
     *
     * @return the value of city.city_name
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_name
     *
     * @param cityName the value for city.city_name
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_py
     *
     * @return the value of city.city_py
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getCityPy() {
        return cityPy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_py
     *
     * @param cityPy the value for city.city_py
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setCityPy(String cityPy) {
        this.cityPy = cityPy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.prov_id
     *
     * @return the value of city.prov_id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public Integer getProvId() {
        return provId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.prov_id
     *
     * @param provId the value for city.prov_id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setProvId(Integer provId) {
        this.provId = provId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_state
     *
     * @return the value of city.city_state
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getCityState() {
        return cityState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_state
     *
     * @param cityState the value for city.city_state
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setCityState(String cityState) {
        this.cityState = cityState;
    }
}