package com.xsx.domain;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.name
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.descript
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    private String descript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.createDate
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.statu
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    private Integer statu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.name
     *
     * @return the value of department.name
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.name
     *
     * @param name the value for department.name
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.descript
     *
     * @return the value of department.descript
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.descript
     *
     * @param descript the value for department.descript
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    public void setDescript(String descript) {
        this.descript = descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.createDate
     *
     * @return the value of department.createDate
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.createDate
     *
     * @param createdate the value for department.createDate
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.statu
     *
     * @return the value of department.statu
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    public Integer getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.statu
     *
     * @param statu the value for department.statu
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    public void setStatu(Integer statu) {
        this.statu = statu;
    }
}