package com.xsx.domain;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String name;
    
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.phone
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.createDate
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.extensionurl
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String extensionurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.extensioncore
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String extensioncore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.img
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.roleid
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.statu
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private Integer statu;
    
    private Integer departmentid;
    
    private String departmentName;
    
    private String extensionrandomcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.phone
     *
     * @return the value of employee.phone
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.phone
     *
     * @param phone the value for employee.phone
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.createDate
     *
     * @return the value of employee.createDate
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.createDate
     *
     * @param createdate the value for employee.createDate
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.extensionurl
     *
     * @return the value of employee.extensionurl
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getExtensionurl() {
        return extensionurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.extensionurl
     *
     * @param extensionurl the value for employee.extensionurl
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setExtensionurl(String extensionurl) {
        this.extensionurl = extensionurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.extensioncore
     *
     * @return the value of employee.extensioncore
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getExtensioncore() {
        return extensioncore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.extensioncore
     *
     * @param extensioncore the value for employee.extensioncore
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setExtensioncore(String extensioncore) {
        this.extensioncore = extensioncore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.img
     *
     * @return the value of employee.img
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.img
     *
     * @param img the value for employee.img
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.roleid
     *
     * @return the value of employee.roleid
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.roleid
     *
     * @param roleid the value for employee.roleid
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.statu
     *
     * @return the value of employee.statu
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public Integer getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.statu
     *
     * @param statu the value for employee.statu
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setStatu(Integer statu) {
        this.statu = statu;
    }

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getDepartmentid() {
		return departmentid;
	}

	public void setDepartmentid(Integer departmentid) {
		this.departmentid = departmentid;
	}

	public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getExtensionrandomcode() {
		return extensionrandomcode;
	}

	public void setExtensionrandomcode(String extensionrandomcode) {
		this.extensionrandomcode = extensionrandomcode;
	}
	
}