package com.xsx.domain;

public class LogInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.id
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.createDate
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.operUser
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    private String operuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.operUrl
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    private String operurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.errormessage
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    private String errormessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.id
     *
     * @return the value of loginfo.id
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.id
     *
     * @param id the value for loginfo.id
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.createDate
     *
     * @return the value of loginfo.createDate
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.createDate
     *
     * @param createdate the value for loginfo.createDate
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.operUser
     *
     * @return the value of loginfo.operUser
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    public String getOperuser() {
        return operuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.operUser
     *
     * @param operuser the value for loginfo.operUser
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    public void setOperuser(String operuser) {
        this.operuser = operuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.operUrl
     *
     * @return the value of loginfo.operUrl
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    public String getOperurl() {
        return operurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.operUrl
     *
     * @param operurl the value for loginfo.operUrl
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    public void setOperurl(String operurl) {
        this.operurl = operurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.errormessage
     *
     * @return the value of loginfo.errormessage
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    public String getErrormessage() {
        return errormessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.errormessage
     *
     * @param errormessage the value for loginfo.errormessage
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    public void setErrormessage(String errormessage) {
        this.errormessage = errormessage;
    }
}