package com.xsx.domain;

public class PhonePayType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phonepaytype.id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phonepaytype.name
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phonepaytype.price
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phonepaytype.createDate
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phonepaytype.statu
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private Integer statu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phonepaytype.id
     *
     * @return the value of phonepaytype.id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phonepaytype.id
     *
     * @param id the value for phonepaytype.id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phonepaytype.name
     *
     * @return the value of phonepaytype.name
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phonepaytype.name
     *
     * @param name the value for phonepaytype.name
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phonepaytype.price
     *
     * @return the value of phonepaytype.price
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phonepaytype.price
     *
     * @param price the value for phonepaytype.price
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phonepaytype.createDate
     *
     * @return the value of phonepaytype.createDate
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phonepaytype.createDate
     *
     * @param createdate the value for phonepaytype.createDate
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phonepaytype.statu
     *
     * @return the value of phonepaytype.statu
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public Integer getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phonepaytype.statu
     *
     * @param statu the value for phonepaytype.statu
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setStatu(Integer statu) {
        this.statu = statu;
    }
}