package com.xsx.domain;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.descript
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String descript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.createDate
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.statu
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private Integer statu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.descript
     *
     * @return the value of role.descript
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.descript
     *
     * @param descript the value for role.descript
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setDescript(String descript) {
        this.descript = descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.createDate
     *
     * @return the value of role.createDate
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.createDate
     *
     * @param createdate the value for role.createDate
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.statu
     *
     * @return the value of role.statu
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public Integer getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.statu
     *
     * @param statu the value for role.statu
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setStatu(Integer statu) {
        this.statu = statu;
    }
}