package com.xsx.domain;

public class Shops {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.title
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.createDate
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.statu
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private Integer statu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.content
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    private String content;
    
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.id
     *
     * @return the value of shops.id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.id
     *
     * @param id the value for shops.id
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.title
     *
     * @return the value of shops.title
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.title
     *
     * @param title the value for shops.title
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.createDate
     *
     * @return the value of shops.createDate
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.createDate
     *
     * @param createdate the value for shops.createDate
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.statu
     *
     * @return the value of shops.statu
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public Integer getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.statu
     *
     * @param statu the value for shops.statu
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setStatu(Integer statu) {
        this.statu = statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.content
     *
     * @return the value of shops.content
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.content
     *
     * @param content the value for shops.content
     *
     * @mbggenerated Tue Oct 31 11:27:22 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}