package com.xsx.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.xsx.domain.Department;
import com.xsx.domain.Page;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    Department selectByPrimaryKey(Integer id);
    
    Department selectByName(@Param("name") String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Thu Nov 02 09:54:52 CST 2017
     */
    int updateByPrimaryKey(Department record);
    
    List<Department> selectAllDepartment(Department department,
			Page<Department> page);
    
    List<Department> selectDepartmentList();
}