package com.xsx.mapper;

import com.xsx.domain.LogInfo;

public interface LogInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    int insert(LogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    int insertSelective(LogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    LogInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    int updateByPrimaryKeySelective(LogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(LogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbggenerated Tue Oct 31 13:06:40 CST 2017
     */
    int updateByPrimaryKey(LogInfo record);
}