package com.xsx.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.xsx.domain.Orders;
import com.xsx.domain.Page;

public interface OrdersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated Tue Oct 31 11:27:22 CST 2017
	 */
	int insert(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated Tue Oct 31 11:27:22 CST 2017
	 */
	int insertSelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated Tue Oct 31 11:27:22 CST 2017
	 */
	Orders selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated Tue Oct 31 11:27:22 CST 2017
	 */
	int updateByPrimaryKeySelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated Tue Oct 31 11:27:22 CST 2017
	 */
	int updateByPrimaryKey(Orders record);

	/**
	 * 今日订单量
	 * 
	 * @param empId
	 * @return
	 */
	Integer todayOrderCount(@Param("empId") Integer empId);

	/**
	 * 昨日订单量
	 * 
	 * @param empId
	 * @return
	 */
	Integer yesterOrderCount(@Param("empId") Integer empId);

	/**
	 * 本月订单量
	 * 
	 * @param empId
	 * @return
	 */
	Integer theMonthOrderCount(@Param("empId") Integer empId);

	/**
	 * 上月订单量
	 * 
	 * @param empId
	 * @return
	 */
	Integer lastMonthOrderCount(@Param("empId") Integer empId);

	/**
	 * 员工所有订单量
	 * 
	 * @param empId
	 * @return
	 */
	Integer employeeOrderCount(@Param("empId") Integer empId);

	/**
	 * 根据员工id查询员工订单
	 * 
	 * @param empId
	 * @return
	 */
	List<Orders> selectOrderByEmpId(@Param("empId") Integer empId);
	
	/**
	 * 查看全部订单
	 * @param orders
	 * @param page
	 * @return
	 */
	List<Orders> selectAllOrders(Orders orders,Page<Orders> page);
	
	/**
	 * 根据客户端ip和员工id查询
	 * @param clientIP
	 * @param id
	 * @return
	 */
	Orders selectByEmpIdAndClientIP(@Param("clientIP") String clientIP, @Param("empId") Integer empId);
	
	
}